### ISSUE TITLE
Yuglify fails to parse jquery.js

### ISSUE THREAD

**Issue by jdufresne** [yui/yuglify#19]
Steps to reproduce: 

``` bash
$ rm -rf bower_components && bower cache clean && bower install jquery#~1.11
bower deleted       Cached package jquery: /home/jon/.cache/bower/packages/fe2fe255e91d251051d543998aa8327a/1.11.0
bower jquery#~1.11          not-cached git://github.com/jquery/jquery.git#~1.11
bower jquery#~1.11             resolve git://github.com/jquery/jquery.git#~1.11
bower jquery#~1.11            download https://github.com/jquery/jquery/archive/1.11.0.tar.gz
bower jquery#~1.11             extract archive.tar.gz
bower jquery#~1.11            resolved git://github.com/jquery/jquery.git#1.11.0
bower jquery#~1.11             install jquery#1.11.0

jquery#1.11.0 bower_components/jquery

$ yuglify bower_components/jquery/dist/jquery.js 
Compressing bower_components/jquery/dist/jquery.js...

/home/jon/node_modules/yuglify/bin/yuglify:111
                    throw(err);
                          ^
Error
    at new JS_Parse_Error (/home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:263:18)
    at js_error (/home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:271:11)
    at croak (/home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:733:9)
    at token_error (/home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:740:9)
    at unexpected (/home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:746:9)
    at /home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1112:13
    at maybe_unary (/home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1209:19)
    at expr_ops (/home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1236:24)
    at maybe_conditional (/home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1240:20)
    at maybe_assign (/home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1264:20)
    at /home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1278:20
    at vardefs (/home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1065:32)
    at var_ (/home/jon/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1077:26)
```

This failure to parse occurred some time between jQuery 1.10 and 1.11 as 1.10 parses fine:

``` bash
$ rm -rf bower_components && bower cache clean && bower install jquery#~1.10
bower deleted       Cached package jquery: /home/jon/.cache/bower/packages/fe2fe255e91d251051d543998aa8327a/1.10.2
bower jquery#~1.10          not-cached git://github.com/jquery/jquery.git#~1.10
bower jquery#~1.10             resolve git://github.com/jquery/jquery.git#~1.10
bower jquery#~1.10            download https://github.com/jquery/jquery/archive/1.10.2.tar.gz
bower jquery#~1.10             extract archive.tar.gz
bower jquery#~1.10            resolved git://github.com/jquery/jquery.git#1.10.2
bower jquery#~1.10             install jquery#1.10.2

jquery#1.10.2 bower_components/jquery

$ yuglify bower_components/jquery/jquery.js 
Compressing bower_components/jquery/jquery.js...
Successfully generated JS file: bower_components/jquery/jquery.min.js
```

I submitted a bug to jQuery, but they believe this is a Yuglify bug. See: http://bugs.jquery.com/ticket/14998

**Comment by LRPalacios** [comment]
any updates on this one? i can confirm too that by removing the two comment blocks starting with /*! resolves the compile issue.

**Comment by sassanh** [comment]
any workaround except changing jquery's code?

**Comment by apendua** [comment]
Same story, here. BTW, I am wondering why `yuglify` fails to show a comprehensive error message.

**Comment by apendua** [comment]
Lemme explain why this is happening. When you look at the `jquery` source code at the beginning of `Sizzle` section, line 548 in my case, you will see this:
```javascript
var Sizzle =
/*!
 * Sizzle CSS Selector Engine v2.2.0-pre
 * http://sizzlejs.com/
 *
 * Copyright 2008, 2014 jQuery Foundation, Inc. and other contributors
 * Released under the MIT license
 * http://jquery.org/license
 *
 * Date: 2014-12-16
 */
(function( window ) {
  // ...
});
```
which looks totally fine at first sight. However, during the compilation process `yuglify` decides to replace the block comment with the following code:
```javascript
var Sizzle =
;"yUglify: preserved comment block";
(function( window ) {
  // ...
});
```
This fails to be a valid JavaScript.

So the question here is why do we want to replace a block comment with something which has  a semantic meaning. I think everyone understand the reason something has to be done, because otherwise the minify process might break things. However, we could replace that block comment with something more like:
```
/* */
```
which should not break anything and it's shorter then the current solution.

**Comment by apendua** [comment]
Ah! I can see what you did there

https://github.com/yui/yuglify/blob/master/lib/jsminify.js#L44-L50

I understand that this is a hack there to prevent  `uglify-js` from removing those comments. Hmm ... I think that this issue shows that the hack is not good enough.

**Comment by apendua** [comment]
Turns out, not having an ability to preserve "license" comments is a long exiting issue in `uglify-js`.

**Comment by apendua** [comment]
BTW, have you considered using

https://github.com/mishoo/UglifyJS2

instead?

**Comment by apendua** [comment]
Ha! I've seen there's already an issue for this #7.

**Comment by jjmurre** [comment]
@apendua: After hours of hair-pulling I came across this discussion. Just switched from Yugilfy to UglifyJS2, problem gone. Tx.

**Comment by jonykalavera** [comment]
I'm just adding jQuery to a static files work-flow for my project, so I just changed to the already minified version of jQuery which doesn't have the evil comments discussed earlier. I realize this isn't even a workaround for the issue at hand but it might be helpful for some people.

**Comment by apendua** [comment]
@jonykalavera Nice trick :+1:

**Comment by mnazim** [comment]
Using jquery.min.js instead of jquery.js solved the issue for me.

**Comment by jplehmann** [comment]
I got burned by this problem this AM -- not from jquery but from the minified versions of bootstrap and parsley javascript.  Recommend generalizing the name of this issue.  +1 for some kind of fix.

**Comment by tjwudi** [comment]
@jonykalavera it works! thanks! :) I wonder if this issue is being working on or not?

**Comment by BarnabasSzabolcs** [comment]
I thought it was still an issue with jQuery 3.4.1 and 3.5.0. minified and non-minified both.

I was using django-compressor, and it turns out, this is the right config:

```
COMPRESS_JS_FILTERS = [
  #'compressor.filters.jsmin.JSMinFilter', # < have to skip this (noob I know :o)
  'compressor.filters.yuglify.YUglifyJSFilter',
]
```
